[package]
name = "gbjam"
version = "0.2.7"
edition = "2021"

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
pathfinding = "4.3.1"
ron = "0.8.1"
bevy = "0.11.2"
bevy-inspector-egui = "0.19.0"
